social-media-publisher:
  principal-names-allowed:
    linkedin: xxx

amazon:
  dynamodb:
    accesskey: xxx
    secretkey: xxx

spring:
  security:
    oauth2:
      client:
        registration:
          linkedin:
            client-id: xxx
            client-secret: xxx
            client-authentication-method: post
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            scope:
              - openid
              - profile
              - email
              - w_member_social
        provider:
          linkedin:
            authorization-uri: https://www.linkedin.com/oauth/v2/authorization
            token-uri: https://www.linkedin.com/oauth/v2/accessToken
            user-info-uri: https://api.linkedin.com/v2/userinfo
            user-name-attribute: id
            jwk-set-uri: https://www.linkedin.com/oauth/openid/jwks