# Reduce logging level to make sure the application works with SAM local
# https://github.com/awslabs/aws-serverless-java-container/issues/134
#logging:
#  level:
#    root: WARN

spring:
  profiles:
    group:
      itest: linkedin
  mail:
    properties:
      "[mail.smtp.auth]": true
      "[mail.smtp.starttls.enable]": true
      "[mail.smtp.connectiontimeout]": 5000
      "[mail.smtp.timeout]": 3000
      "[mail.smtp.writetimeout]": 5000
    host: smtp.gmail.com
    password: xxxxx
    username: yyyyy
    port: 587

social-media-publisher:
  post:
    mail:
      sender-email: sender@mail.com
      receiver-email: receiver@mail.com
  linked-in:
    base-url: https://api.linkedin.com
  credentials:
    login-host: 'http://localhost:8080'
    login-url: '${social-media-publisher.credentials.login-host}/oauth2/{social-media-id}/credentials'
