package com.coderstower.socialmediapubisher.main.aws.repository.post;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.coderstower.socialmediapubisher.main.aws.repository.URLConverter;
import com.coderstower.socialmediapubisher.main.aws.repository.LocalDateTimeConverter;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.net.URL;
import java.time.LocalDateTime;
import java.util.List;

@Data
@DynamoDBTable(tableName = "Posts")
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class PostDynamo {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;
    @DynamoDBAttribute
    private String name;
    @DynamoDBAttribute
    private String description;
    @DynamoDBAttribute
    private List<String> tags;
    @DynamoDBAttribute
    @DynamoDBTypeConverted(converter = URLConverter.class)
    private URL url;
    @DynamoDBAttribute
    @DynamoDBTypeConverted(converter = LocalDateTimeConverter.class)
    private LocalDateTime publishedDate;
    @DynamoDBAttribute
    private String group;
}
